### ISSUE TITLE
CR

### ISSUE THREAD

**Issue by MonicaLLLMMM** [iris-shanghai/mens#1]
把最后一段活动规则的字段拿掉

**Comment by iamike** [comment]
是哪一段，please attach screen shot

**Comment by MonicaLLLMMM** [comment]
![img_1053](https://cloud.githubusercontent.com/assets/16282946/11772186/bcc7d496-a254-11e5-9173-e2f881e854ef.JPG)

**Comment by iamike** [comment]
Hi Monica, 
this issue has been fixed, please review:
http://yioulai.com/europe/mens/
thanks

**Comment by MonicaLLLMMM** [comment]
ok thanks mike
