### ISSUE TITLE
cr2

### ISSUE THREAD

**Issue by MonicaLLLMMM** [iris-shanghai/mens#2]

**Comment by MonicaLLLMMM** [comment]
Hi Mike,

CNY village offer的页面还有一些小调整要改，主要都是在文字的细节上，什么多出空格打错字之类。我全部标出来放在ppt里了，另外要替换的图片在单独的文件夹里。

下载链接：http://pan.baidu.com/s/1o7dWoP0

麻烦对着ppt每一页每个点进行修改，谢谢。

有问题告诉我，图片如果需要裁剪的问题请nango帮忙，我跟他说过了。

这个很急哦，今天要全部弄好，我再全部检查好没问题了以后今天要上线。谢谢。

Monica

**Comment by iamike** [comment]
please review:
http://yioulai.com/europe/wechatCampaign/

**Comment by MonicaLLLMMM** [comment]
Hi Mike,

Found 2 small issues for village 6 and village 9.
1. For village 6, we missed 莲花 in front of the offer
2. For village 9, please delete the space between "私“ and “人” in the last sentence.

please help change them and send me the screenshots for these 2. need to send them to the client asap.

thanks.

Monica
![default](https://cloud.githubusercontent.com/assets/16282946/11778560/0db9692e-a290-11e5-995c-a77b4a00f1af.png)
![default](https://cloud.githubusercontent.com/assets/16282946/11778562/0efa70f8-a290-11e5-9566-94ce28e94304.png)

**Comment by iamike** [comment]
fixed

**Comment by MonicaLLLMMM** [comment]
Hi Mike,

帮忙看下v6的页面图片有没有替换成最新的，假如没有的话帮忙替换下，谢谢。

图片：http://pan.baidu.com/s/1P1GfG

Monica
