### ISSUE TITLE
Change copy

### ISSUE THREAD

**Issue by melanie-sun** [iris-shanghai/mens#8]
Change the copy above the videos to:
时尚视频
伦敦艺术家和明星造型师为你讲述他们的时尚故事
Please use the same format as the copy above the products.

Change the copy under the WeChat QR code to:
即日起至X月X日，关注奕欧来EUROPE微信号，我们将抽取30位幸运粉丝，送出Brooks Brothers精美袖扣。
The date in the copy will be confirmed before the launch of the campaign.

**Comment by iamike** [comment]
Hi Melanie,
this issue has been updated, please review.
http://yioulai.com/europe/mens/

thanks

Mike

**Comment by melanie-sun** [comment]
Hi Mike,

Please change the format of the copy above the products to the same as the copy above the videos.

Thanks

Mel

**Comment by iamike** [comment]
Hi Melanie,
this issue has been fixed, please review
http://yioulai.com/europe/mens/
thanks

Mike

**Comment by melanie-sun** [comment]
Thanks Mike.

**Comment by Beepengtan** [comment]
fixed no problem
