### ISSUE TITLE
T&C

### ISSUE THREAD

**Issue by melanie-sun** [iris-shanghai/mens#9]
Hi Mike,

Could you add a button （查看活动详情）at the bottom of the landing page. When user clicks on the button, a pop up window will show the T&C.

I've attached T&C as below:
[Men's Campaign T&C (CN).docx](https://github.com/iris-shanghai/mens/files/68115/Men.s.Campaign.T.C.CN.docx)

Sorry to rush you, but we are rushing to launch the campaign today. Hope you get well soon.

Thanks,
Mel

**Comment by iamike** [comment]
Hi Melanie,
this issue has been updated. please review,
http://yioulai.com/europe/mens/#
thanks

Mike
